//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MESSAGEHISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MESSAGEHISTORY()
        {
            this.TBL_MESSAGEATTACHMENTS = new HashSet<TBL_MESSAGEATTACHMENTS>();
        }
    
        public long MessageHistoryId { get; set; }
        public string MessageDetail { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IPAddress { get; set; }
        public bool IsMessageRead { get; set; }
        public bool IsSpam { get; set; }
        public bool IsReported { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MESSAGEATTACHMENTS> TBL_MESSAGEATTACHMENTS { get; set; }
    }
}
