//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WEvahaEntities : DbContext
    {
        public WEvahaEntities()
            : base("name=WEvahaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_MESSAGEATTACHMENTS> TBL_MESSAGEATTACHMENTS { get; set; }
        public virtual DbSet<TBL_MESSAGEHISTORY> TBL_MESSAGEHISTORY { get; set; }
        public virtual DbSet<TBL_MESSAGELABELS> TBL_MESSAGELABELS { get; set; }
        public virtual DbSet<TBL_MESSAGEQUICKRESPONSES> TBL_MESSAGEQUICKRESPONSES { get; set; }
        public virtual DbSet<TBL_MESSAGESTARS> TBL_MESSAGESTARS { get; set; }
        public virtual DbSet<TBL_USER_PROFILE> TBL_USER_PROFILE { get; set; }
        public virtual DbSet<TBL_MESSAGEUSERLABELS> TBL_MESSAGEUSERLABELS { get; set; }
        public virtual DbSet<TBL_MESSAGEARCHIVE> TBL_MESSAGEARCHIVE { get; set; }
    
        public virtual int USP_INSERT_LOG(string lException, string lInnerException, string lUri, ObjectParameter logId)
        {
            var lExceptionParameter = lException != null ?
                new ObjectParameter("LException", lException) :
                new ObjectParameter("LException", typeof(string));
    
            var lInnerExceptionParameter = lInnerException != null ?
                new ObjectParameter("LInnerException", lInnerException) :
                new ObjectParameter("LInnerException", typeof(string));
    
            var lUriParameter = lUri != null ?
                new ObjectParameter("LUri", lUri) :
                new ObjectParameter("LUri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_LOG", lExceptionParameter, lInnerExceptionParameter, lUriParameter, logId);
        }
    
        public virtual int USP_WE_CHANGE_PASSWORD(Nullable<int> profileId, string password)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_CHANGE_PASSWORD", profileIdParameter, passwordParameter);
        }
    
        public virtual ObjectResult<USP_WE_COUNTRY_STATE_CITY_Result> USP_WE_COUNTRY_STATE_CITY(Nullable<int> cOUNTRY_ID, Nullable<int> sTATE_ID, Nullable<int> fLAG)
        {
            var cOUNTRY_IDParameter = cOUNTRY_ID.HasValue ?
                new ObjectParameter("COUNTRY_ID", cOUNTRY_ID) :
                new ObjectParameter("COUNTRY_ID", typeof(int));
    
            var sTATE_IDParameter = sTATE_ID.HasValue ?
                new ObjectParameter("STATE_ID", sTATE_ID) :
                new ObjectParameter("STATE_ID", typeof(int));
    
            var fLAGParameter = fLAG.HasValue ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_COUNTRY_STATE_CITY_Result>("USP_WE_COUNTRY_STATE_CITY", cOUNTRY_IDParameter, sTATE_IDParameter, fLAGParameter);
        }
    
        public virtual ObjectResult<USP_WE_DASHBOARD_GET_WHO_VIEWED_ME_Result> USP_WE_DASHBOARD_GET_WHO_VIEWED_ME(Nullable<int> profileId, Nullable<int> rows)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("Rows", rows) :
                new ObjectParameter("Rows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_DASHBOARD_GET_WHO_VIEWED_ME_Result>("USP_WE_DASHBOARD_GET_WHO_VIEWED_ME", profileIdParameter, rowsParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_ADVANCESEARCH_Result> USP_WE_GET_ADVANCESEARCH(string gENDER, string rELIGION, string lANGUAGE, string cASTE, string aGE_FROM, string aGE_TO, string hEIGHT_FROM, string hEIGHT_TO, string cOUNTRY, string rELATIONSHIPSTATUS, string jOB, string eDUCATION, string sMOKE, string dRINK, string kIDS, string fAITHINGOD, string pETS, string tRAVEL, string mOVIES, string sHOPPING, Nullable<int> pROFILEID)
        {
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            var rELIGIONParameter = rELIGION != null ?
                new ObjectParameter("RELIGION", rELIGION) :
                new ObjectParameter("RELIGION", typeof(string));
    
            var lANGUAGEParameter = lANGUAGE != null ?
                new ObjectParameter("LANGUAGE", lANGUAGE) :
                new ObjectParameter("LANGUAGE", typeof(string));
    
            var cASTEParameter = cASTE != null ?
                new ObjectParameter("CASTE", cASTE) :
                new ObjectParameter("CASTE", typeof(string));
    
            var aGE_FROMParameter = aGE_FROM != null ?
                new ObjectParameter("AGE_FROM", aGE_FROM) :
                new ObjectParameter("AGE_FROM", typeof(string));
    
            var aGE_TOParameter = aGE_TO != null ?
                new ObjectParameter("AGE_TO", aGE_TO) :
                new ObjectParameter("AGE_TO", typeof(string));
    
            var hEIGHT_FROMParameter = hEIGHT_FROM != null ?
                new ObjectParameter("HEIGHT_FROM", hEIGHT_FROM) :
                new ObjectParameter("HEIGHT_FROM", typeof(string));
    
            var hEIGHT_TOParameter = hEIGHT_TO != null ?
                new ObjectParameter("HEIGHT_TO", hEIGHT_TO) :
                new ObjectParameter("HEIGHT_TO", typeof(string));
    
            var cOUNTRYParameter = cOUNTRY != null ?
                new ObjectParameter("COUNTRY", cOUNTRY) :
                new ObjectParameter("COUNTRY", typeof(string));
    
            var rELATIONSHIPSTATUSParameter = rELATIONSHIPSTATUS != null ?
                new ObjectParameter("RELATIONSHIPSTATUS", rELATIONSHIPSTATUS) :
                new ObjectParameter("RELATIONSHIPSTATUS", typeof(string));
    
            var jOBParameter = jOB != null ?
                new ObjectParameter("JOB", jOB) :
                new ObjectParameter("JOB", typeof(string));
    
            var eDUCATIONParameter = eDUCATION != null ?
                new ObjectParameter("EDUCATION", eDUCATION) :
                new ObjectParameter("EDUCATION", typeof(string));
    
            var sMOKEParameter = sMOKE != null ?
                new ObjectParameter("SMOKE", sMOKE) :
                new ObjectParameter("SMOKE", typeof(string));
    
            var dRINKParameter = dRINK != null ?
                new ObjectParameter("DRINK", dRINK) :
                new ObjectParameter("DRINK", typeof(string));
    
            var kIDSParameter = kIDS != null ?
                new ObjectParameter("KIDS", kIDS) :
                new ObjectParameter("KIDS", typeof(string));
    
            var fAITHINGODParameter = fAITHINGOD != null ?
                new ObjectParameter("FAITHINGOD", fAITHINGOD) :
                new ObjectParameter("FAITHINGOD", typeof(string));
    
            var pETSParameter = pETS != null ?
                new ObjectParameter("PETS", pETS) :
                new ObjectParameter("PETS", typeof(string));
    
            var tRAVELParameter = tRAVEL != null ?
                new ObjectParameter("TRAVEL", tRAVEL) :
                new ObjectParameter("TRAVEL", typeof(string));
    
            var mOVIESParameter = mOVIES != null ?
                new ObjectParameter("MOVIES", mOVIES) :
                new ObjectParameter("MOVIES", typeof(string));
    
            var sHOPPINGParameter = sHOPPING != null ?
                new ObjectParameter("SHOPPING", sHOPPING) :
                new ObjectParameter("SHOPPING", typeof(string));
    
            var pROFILEIDParameter = pROFILEID.HasValue ?
                new ObjectParameter("PROFILEID", pROFILEID) :
                new ObjectParameter("PROFILEID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_ADVANCESEARCH_Result>("USP_WE_GET_ADVANCESEARCH", gENDERParameter, rELIGIONParameter, lANGUAGEParameter, cASTEParameter, aGE_FROMParameter, aGE_TOParameter, hEIGHT_FROMParameter, hEIGHT_TOParameter, cOUNTRYParameter, rELATIONSHIPSTATUSParameter, jOBParameter, eDUCATIONParameter, sMOKEParameter, dRINKParameter, kIDSParameter, fAITHINGODParameter, pETSParameter, tRAVELParameter, mOVIESParameter, sHOPPINGParameter, pROFILEIDParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_BASICSEARCH_Result> USP_WE_GET_BASICSEARCH(Nullable<int> sGENDER, string aGE_FROM, string aGE_TO, string rELIGION, string cASTE, string lANGUAGE, Nullable<int> profileId)
        {
            var sGENDERParameter = sGENDER.HasValue ?
                new ObjectParameter("SGENDER", sGENDER) :
                new ObjectParameter("SGENDER", typeof(int));
    
            var aGE_FROMParameter = aGE_FROM != null ?
                new ObjectParameter("AGE_FROM", aGE_FROM) :
                new ObjectParameter("AGE_FROM", typeof(string));
    
            var aGE_TOParameter = aGE_TO != null ?
                new ObjectParameter("AGE_TO", aGE_TO) :
                new ObjectParameter("AGE_TO", typeof(string));
    
            var rELIGIONParameter = rELIGION != null ?
                new ObjectParameter("RELIGION", rELIGION) :
                new ObjectParameter("RELIGION", typeof(string));
    
            var cASTEParameter = cASTE != null ?
                new ObjectParameter("CASTE", cASTE) :
                new ObjectParameter("CASTE", typeof(string));
    
            var lANGUAGEParameter = lANGUAGE != null ?
                new ObjectParameter("LANGUAGE", lANGUAGE) :
                new ObjectParameter("LANGUAGE", typeof(string));
    
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_BASICSEARCH_Result>("USP_WE_GET_BASICSEARCH", sGENDERParameter, aGE_FROMParameter, aGE_TOParameter, rELIGIONParameter, cASTEParameter, lANGUAGEParameter, profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_CASTE_Result> USP_WE_GET_CASTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_CASTE_Result>("USP_WE_GET_CASTE");
        }
    
        public virtual ObjectResult<USP_WE_GET_CASTE_BY_LANGUAGE_Result> USP_WE_GET_CASTE_BY_LANGUAGE(Nullable<int> languageId)
        {
            var languageIdParameter = languageId.HasValue ?
                new ObjectParameter("LanguageId", languageId) :
                new ObjectParameter("LanguageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_CASTE_BY_LANGUAGE_Result>("USP_WE_GET_CASTE_BY_LANGUAGE", languageIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_CITY_BY_STATE_Result> USP_WE_GET_CITY_BY_STATE(Nullable<int> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_CITY_BY_STATE_Result>("USP_WE_GET_CITY_BY_STATE", stateIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_COMPATABLE_MATCHES_IN_BASICSEARCH_Result> USP_WE_GET_COMPATABLE_MATCHES_IN_BASICSEARCH(Nullable<int> sGENDER, string aGE_FROM, string aGE_TO, string rELIGION, string cASTE, string lANGUAGE, Nullable<int> profileId)
        {
            var sGENDERParameter = sGENDER.HasValue ?
                new ObjectParameter("SGENDER", sGENDER) :
                new ObjectParameter("SGENDER", typeof(int));
    
            var aGE_FROMParameter = aGE_FROM != null ?
                new ObjectParameter("AGE_FROM", aGE_FROM) :
                new ObjectParameter("AGE_FROM", typeof(string));
    
            var aGE_TOParameter = aGE_TO != null ?
                new ObjectParameter("AGE_TO", aGE_TO) :
                new ObjectParameter("AGE_TO", typeof(string));
    
            var rELIGIONParameter = rELIGION != null ?
                new ObjectParameter("RELIGION", rELIGION) :
                new ObjectParameter("RELIGION", typeof(string));
    
            var cASTEParameter = cASTE != null ?
                new ObjectParameter("CASTE", cASTE) :
                new ObjectParameter("CASTE", typeof(string));
    
            var lANGUAGEParameter = lANGUAGE != null ?
                new ObjectParameter("LANGUAGE", lANGUAGE) :
                new ObjectParameter("LANGUAGE", typeof(string));
    
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_COMPATABLE_MATCHES_IN_BASICSEARCH_Result>("USP_WE_GET_COMPATABLE_MATCHES_IN_BASICSEARCH", sGENDERParameter, aGE_FROMParameter, aGE_TOParameter, rELIGIONParameter, cASTEParameter, lANGUAGEParameter, profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_COVER_PHOTO_BY_ID_Result> USP_WE_GET_COVER_PHOTO_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_COVER_PHOTO_BY_ID_Result>("USP_WE_GET_COVER_PHOTO_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_ETHNICITY_Result> USP_WE_GET_ETHNICITY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_ETHNICITY_Result>("USP_WE_GET_ETHNICITY");
        }
    
        public virtual ObjectResult<USP_WE_GET_HIGHT_Result> USP_WE_GET_HIGHT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_HIGHT_Result>("USP_WE_GET_HIGHT");
        }
    
        public virtual ObjectResult<USP_WE_GET_LANGUAGE_Result> USP_WE_GET_LANGUAGE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_LANGUAGE_Result>("USP_WE_GET_LANGUAGE");
        }
    
        public virtual ObjectResult<USP_WE_GET_PACKAGES_Result> USP_WE_GET_PACKAGES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PACKAGES_Result>("USP_WE_GET_PACKAGES");
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_BY_ID_Result> USP_WE_GET_PROFILE_BY_ID(Nullable<int> vProfileId, Nullable<int> profileId)
        {
            var vProfileIdParameter = vProfileId.HasValue ?
                new ObjectParameter("vProfileId", vProfileId) :
                new ObjectParameter("vProfileId", typeof(int));
    
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_BY_ID_Result>("USP_WE_GET_PROFILE_BY_ID", vProfileIdParameter, profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_BY_ID_FOR_UPDATE_Result> USP_WE_GET_PROFILE_BY_ID_FOR_UPDATE(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_BY_ID_FOR_UPDATE_Result>("USP_WE_GET_PROFILE_BY_ID_FOR_UPDATE", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_HOBBIES_BY_ID_Result> USP_WE_GET_PROFILE_HOBBIES_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_HOBBIES_BY_ID_Result>("USP_WE_GET_PROFILE_HOBBIES_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<string> USP_WE_GET_PROFILE_MOBILE_NUMBER_BY_ID(Nullable<int> vProfileId, Nullable<int> profileId, ObjectParameter sResult)
        {
            var vProfileIdParameter = vProfileId.HasValue ?
                new ObjectParameter("vProfileId", vProfileId) :
                new ObjectParameter("vProfileId", typeof(int));
    
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_WE_GET_PROFILE_MOBILE_NUMBER_BY_ID", vProfileIdParameter, profileIdParameter, sResult);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_PERSONALCHOICES_BY_ID_Result> USP_WE_GET_PROFILE_PERSONALCHOICES_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_PERSONALCHOICES_BY_ID_Result>("USP_WE_GET_PROFILE_PERSONALCHOICES_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_PERSONALDETAILS_BY_ID_Result> USP_WE_GET_PROFILE_PERSONALDETAILS_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_PERSONALDETAILS_BY_ID_Result>("USP_WE_GET_PROFILE_PERSONALDETAILS_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_PERSONALVIEWS_BY_ID_Result> USP_WE_GET_PROFILE_PERSONALVIEWS_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_PERSONALVIEWS_BY_ID_Result>("USP_WE_GET_PROFILE_PERSONALVIEWS_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_PHOTOS_BY_ID_Result> USP_WE_GET_PROFILE_PHOTOS_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_PHOTOS_BY_ID_Result>("USP_WE_GET_PROFILE_PHOTOS_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_PIC_BY_ID_Result> USP_WE_GET_PROFILE_PIC_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_PIC_BY_ID_Result>("USP_WE_GET_PROFILE_PIC_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_SELEFDESCRIPTION_BY_ID_Result> USP_WE_GET_PROFILE_SELEFDESCRIPTION_BY_ID(Nullable<int> vProfileId)
        {
            var vProfileIdParameter = vProfileId.HasValue ?
                new ObjectParameter("vProfileId", vProfileId) :
                new ObjectParameter("vProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_SELEFDESCRIPTION_BY_ID_Result>("USP_WE_GET_PROFILE_SELEFDESCRIPTION_BY_ID", vProfileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_SELFDESCRIPTION_BY_ID_Result> USP_WE_GET_PROFILE_SELFDESCRIPTION_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_SELFDESCRIPTION_BY_ID_Result>("USP_WE_GET_PROFILE_SELFDESCRIPTION_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_WHOAMI_BY_ID_Result> USP_WE_GET_PROFILE_WHOAMI_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_WHOAMI_BY_ID_Result>("USP_WE_GET_PROFILE_WHOAMI_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_RECENT_VISITORS_Result> USP_WE_GET_RECENT_VISITORS(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_RECENT_VISITORS_Result>("USP_WE_GET_RECENT_VISITORS", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_RELIGION_Result> USP_WE_GET_RELIGION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_RELIGION_Result>("USP_WE_GET_RELIGION");
        }
    
        public virtual ObjectResult<USP_WE_GET_STATE_BY_COUNTRY_Result> USP_WE_GET_STATE_BY_COUNTRY(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_STATE_BY_COUNTRY_Result>("USP_WE_GET_STATE_BY_COUNTRY", countryIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_SUB_CASTE_Result> USP_WE_GET_SUB_CASTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_SUB_CASTE_Result>("USP_WE_GET_SUB_CASTE");
        }
    
        public virtual ObjectResult<USP_WE_GET_USER_FAVOURITES_Result> USP_WE_GET_USER_FAVOURITES(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_USER_FAVOURITES_Result>("USP_WE_GET_USER_FAVOURITES", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_USER_PACKAGE_DETAILS_Result> USP_WE_GET_USER_PACKAGE_DETAILS(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_USER_PACKAGE_DETAILS_Result>("USP_WE_GET_USER_PACKAGE_DETAILS", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_USER_PROFILE_BY_ID_Result> USP_WE_GET_USER_PROFILE_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_USER_PROFILE_BY_ID_Result>("USP_WE_GET_USER_PROFILE_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_WHO_VIEWED_ME_Result> USP_WE_GET_WHO_VIEWED_ME(Nullable<int> profileID)
        {
            var profileIDParameter = profileID.HasValue ?
                new ObjectParameter("ProfileID", profileID) :
                new ObjectParameter("ProfileID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_WHO_VIEWED_ME_Result>("USP_WE_GET_WHO_VIEWED_ME", profileIDParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_WHO_VIEWED_MY_PROFILE_Result> USP_WE_GET_WHO_VIEWED_MY_PROFILE(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_WHO_VIEWED_MY_PROFILE_Result>("USP_WE_GET_WHO_VIEWED_MY_PROFILE", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GETCASTE_Result> USP_WE_GETCASTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETCASTE_Result>("USP_WE_GETCASTE");
        }
    
        public virtual ObjectResult<USP_WE_GETCHATUSERWITHMSGCOUNT_Result> USP_WE_GETCHATUSERWITHMSGCOUNT(Nullable<int> currentUserId)
        {
            var currentUserIdParameter = currentUserId.HasValue ?
                new ObjectParameter("CurrentUserId", currentUserId) :
                new ObjectParameter("CurrentUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETCHATUSERWITHMSGCOUNT_Result>("USP_WE_GETCHATUSERWITHMSGCOUNT", currentUserIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GETCITY_Result> USP_WE_GETCITY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETCITY_Result>("USP_WE_GETCITY");
        }
    
        public virtual ObjectResult<USP_WE_GETCOUNTRY_Result> USP_WE_GETCOUNTRY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETCOUNTRY_Result>("USP_WE_GETCOUNTRY");
        }
    
        public virtual ObjectResult<USP_WE_GETLOOKUPVALUE_Result> USP_WE_GETLOOKUPVALUE(string lookupType)
        {
            var lookupTypeParameter = lookupType != null ?
                new ObjectParameter("LookupType", lookupType) :
                new ObjectParameter("LookupType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETLOOKUPVALUE_Result>("USP_WE_GETLOOKUPVALUE", lookupTypeParameter);
        }
    
        public virtual ObjectResult<USP_WE_GETMESSAGEHISTORYBYID_Result> USP_WE_GETMESSAGEHISTORYBYID(Nullable<int> fromUserId, Nullable<int> toUserId, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var fromUserIdParameter = fromUserId.HasValue ?
                new ObjectParameter("FromUserId", fromUserId) :
                new ObjectParameter("FromUserId", typeof(int));
    
            var toUserIdParameter = toUserId.HasValue ?
                new ObjectParameter("ToUserId", toUserId) :
                new ObjectParameter("ToUserId", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETMESSAGEHISTORYBYID_Result>("USP_WE_GETMESSAGEHISTORYBYID", fromUserIdParameter, toUserIdParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<USP_WE_GETOCCUPATION_Result> USP_WE_GETOCCUPATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETOCCUPATION_Result>("USP_WE_GETOCCUPATION");
        }
    
        public virtual ObjectResult<USP_WE_GETSTATE_Result> USP_WE_GETSTATE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETSTATE_Result>("USP_WE_GETSTATE");
        }
    
        public virtual ObjectResult<USP_WE_GETSUBCASTE_Result> USP_WE_GETSUBCASTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GETSUBCASTE_Result>("USP_WE_GETSUBCASTE");
        }
    
        public virtual ObjectResult<string> USP_WE_INSERT_COVER_PHOTO(Nullable<int> profileId, string photoNameExt, ObjectParameter optimizedphotourl)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var photoNameExtParameter = photoNameExt != null ?
                new ObjectParameter("PhotoNameExt", photoNameExt) :
                new ObjectParameter("PhotoNameExt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_WE_INSERT_COVER_PHOTO", profileIdParameter, photoNameExtParameter, optimizedphotourl);
        }
    
        public virtual int USP_WE_INSERT_PROFILE(string profileName, string email, string password, Nullable<int> gender, Nullable<int> seekingGender, string zipcode, Nullable<int> country, string howDidYouHearAboutUs, string activationCode, ObjectParameter profileId)
        {
            var profileNameParameter = profileName != null ?
                new ObjectParameter("ProfileName", profileName) :
                new ObjectParameter("ProfileName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(int));
    
            var seekingGenderParameter = seekingGender.HasValue ?
                new ObjectParameter("SeekingGender", seekingGender) :
                new ObjectParameter("SeekingGender", typeof(int));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(int));
    
            var howDidYouHearAboutUsParameter = howDidYouHearAboutUs != null ?
                new ObjectParameter("HowDidYouHearAboutUs", howDidYouHearAboutUs) :
                new ObjectParameter("HowDidYouHearAboutUs", typeof(string));
    
            var activationCodeParameter = activationCode != null ?
                new ObjectParameter("ActivationCode", activationCode) :
                new ObjectParameter("ActivationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE", profileNameParameter, emailParameter, passwordParameter, genderParameter, seekingGenderParameter, zipcodeParameter, countryParameter, howDidYouHearAboutUsParameter, activationCodeParameter, profileId);
        }
    
        public virtual int USP_WE_INSERT_PROFILE_ABOUTMYSELF(Nullable<int> profileId, string height, string relationshipStatus, string relationshipDetails, string kids, string pets, string wantChildren, string education, string educationDetails, string smoke, string drink, string ethnicity, string religion, string motherTongue, string caste, string subCaste, string foodPreference, string job, string jobDetails, string cityofJob, string stateofJob, string countryofJob)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var heightParameter = height != null ?
                new ObjectParameter("Height", height) :
                new ObjectParameter("Height", typeof(string));
    
            var relationshipStatusParameter = relationshipStatus != null ?
                new ObjectParameter("RelationshipStatus", relationshipStatus) :
                new ObjectParameter("RelationshipStatus", typeof(string));
    
            var relationshipDetailsParameter = relationshipDetails != null ?
                new ObjectParameter("RelationshipDetails", relationshipDetails) :
                new ObjectParameter("RelationshipDetails", typeof(string));
    
            var kidsParameter = kids != null ?
                new ObjectParameter("Kids", kids) :
                new ObjectParameter("Kids", typeof(string));
    
            var petsParameter = pets != null ?
                new ObjectParameter("Pets", pets) :
                new ObjectParameter("Pets", typeof(string));
    
            var wantChildrenParameter = wantChildren != null ?
                new ObjectParameter("WantChildren", wantChildren) :
                new ObjectParameter("WantChildren", typeof(string));
    
            var educationParameter = education != null ?
                new ObjectParameter("Education", education) :
                new ObjectParameter("Education", typeof(string));
    
            var educationDetailsParameter = educationDetails != null ?
                new ObjectParameter("EducationDetails", educationDetails) :
                new ObjectParameter("EducationDetails", typeof(string));
    
            var smokeParameter = smoke != null ?
                new ObjectParameter("Smoke", smoke) :
                new ObjectParameter("Smoke", typeof(string));
    
            var drinkParameter = drink != null ?
                new ObjectParameter("Drink", drink) :
                new ObjectParameter("Drink", typeof(string));
    
            var ethnicityParameter = ethnicity != null ?
                new ObjectParameter("Ethnicity", ethnicity) :
                new ObjectParameter("Ethnicity", typeof(string));
    
            var religionParameter = religion != null ?
                new ObjectParameter("Religion", religion) :
                new ObjectParameter("Religion", typeof(string));
    
            var motherTongueParameter = motherTongue != null ?
                new ObjectParameter("MotherTongue", motherTongue) :
                new ObjectParameter("MotherTongue", typeof(string));
    
            var casteParameter = caste != null ?
                new ObjectParameter("Caste", caste) :
                new ObjectParameter("Caste", typeof(string));
    
            var subCasteParameter = subCaste != null ?
                new ObjectParameter("SubCaste", subCaste) :
                new ObjectParameter("SubCaste", typeof(string));
    
            var foodPreferenceParameter = foodPreference != null ?
                new ObjectParameter("FoodPreference", foodPreference) :
                new ObjectParameter("FoodPreference", typeof(string));
    
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            var jobDetailsParameter = jobDetails != null ?
                new ObjectParameter("JobDetails", jobDetails) :
                new ObjectParameter("JobDetails", typeof(string));
    
            var cityofJobParameter = cityofJob != null ?
                new ObjectParameter("CityofJob", cityofJob) :
                new ObjectParameter("CityofJob", typeof(string));
    
            var stateofJobParameter = stateofJob != null ?
                new ObjectParameter("StateofJob", stateofJob) :
                new ObjectParameter("StateofJob", typeof(string));
    
            var countryofJobParameter = countryofJob != null ?
                new ObjectParameter("CountryofJob", countryofJob) :
                new ObjectParameter("CountryofJob", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE_ABOUTMYSELF", profileIdParameter, heightParameter, relationshipStatusParameter, relationshipDetailsParameter, kidsParameter, petsParameter, wantChildrenParameter, educationParameter, educationDetailsParameter, smokeParameter, drinkParameter, ethnicityParameter, religionParameter, motherTongueParameter, casteParameter, subCasteParameter, foodPreferenceParameter, jobParameter, jobDetailsParameter, cityofJobParameter, stateofJobParameter, countryofJobParameter);
        }
    
        public virtual int USP_WE_INSERT_PROFILE_HOBBIES(Nullable<int> profileId, string carsAndDriving, string spendFreeTime, string sportsILike, string instrumentsIPlay, string music, string vacations, string favorite, string tVShows, string movies, string books, string travel, string excercising, string hiking, string driving, string beaches)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var carsAndDrivingParameter = carsAndDriving != null ?
                new ObjectParameter("CarsAndDriving", carsAndDriving) :
                new ObjectParameter("CarsAndDriving", typeof(string));
    
            var spendFreeTimeParameter = spendFreeTime != null ?
                new ObjectParameter("SpendFreeTime", spendFreeTime) :
                new ObjectParameter("SpendFreeTime", typeof(string));
    
            var sportsILikeParameter = sportsILike != null ?
                new ObjectParameter("SportsILike", sportsILike) :
                new ObjectParameter("SportsILike", typeof(string));
    
            var instrumentsIPlayParameter = instrumentsIPlay != null ?
                new ObjectParameter("InstrumentsIPlay", instrumentsIPlay) :
                new ObjectParameter("InstrumentsIPlay", typeof(string));
    
            var musicParameter = music != null ?
                new ObjectParameter("Music", music) :
                new ObjectParameter("Music", typeof(string));
    
            var vacationsParameter = vacations != null ?
                new ObjectParameter("Vacations", vacations) :
                new ObjectParameter("Vacations", typeof(string));
    
            var favoriteParameter = favorite != null ?
                new ObjectParameter("Favorite", favorite) :
                new ObjectParameter("Favorite", typeof(string));
    
            var tVShowsParameter = tVShows != null ?
                new ObjectParameter("TVShows", tVShows) :
                new ObjectParameter("TVShows", typeof(string));
    
            var moviesParameter = movies != null ?
                new ObjectParameter("Movies", movies) :
                new ObjectParameter("Movies", typeof(string));
    
            var booksParameter = books != null ?
                new ObjectParameter("Books", books) :
                new ObjectParameter("Books", typeof(string));
    
            var travelParameter = travel != null ?
                new ObjectParameter("Travel", travel) :
                new ObjectParameter("Travel", typeof(string));
    
            var excercisingParameter = excercising != null ?
                new ObjectParameter("Excercising", excercising) :
                new ObjectParameter("Excercising", typeof(string));
    
            var hikingParameter = hiking != null ?
                new ObjectParameter("Hiking", hiking) :
                new ObjectParameter("Hiking", typeof(string));
    
            var drivingParameter = driving != null ?
                new ObjectParameter("Driving", driving) :
                new ObjectParameter("Driving", typeof(string));
    
            var beachesParameter = beaches != null ?
                new ObjectParameter("Beaches", beaches) :
                new ObjectParameter("Beaches", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE_HOBBIES", profileIdParameter, carsAndDrivingParameter, spendFreeTimeParameter, sportsILikeParameter, instrumentsIPlayParameter, musicParameter, vacationsParameter, favoriteParameter, tVShowsParameter, moviesParameter, booksParameter, travelParameter, excercisingParameter, hikingParameter, drivingParameter, beachesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_WE_INSERT_PROFILE_OPTIMIZED_PIC(Nullable<int> profileId, string photoUrl, ObjectParameter sResult)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var photoUrlParameter = photoUrl != null ?
                new ObjectParameter("PhotoUrl", photoUrl) :
                new ObjectParameter("PhotoUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_WE_INSERT_PROFILE_OPTIMIZED_PIC", profileIdParameter, photoUrlParameter, sResult);
        }
    
        public virtual int USP_WE_INSERT_PROFILE_PERSONALCHOICES(Nullable<int> profileId, string goals, string friendsNetwork, string friendLaugh, string houseImprovements, string careAbout, string organizedLife, string finances, string homeEntertaining, string caringforChildren, string romanceinRelation, string socializing, string homeEnvironment, string sharingBeliefs, string physicalFit, string calmDuringCrisis, string thoughtsAndfeelings, string helpingFortunates, string resolveConflict, string adventures, string knowledgeAndAwareness, string professionalPlanning, string eventsUnderstanding, string findingPleasure, string cultureAndTradition, string creativeSolutions, string makingFriends, string cookingForFamily, string provideIncomeforFamily, string householdSchedules, string beingAgoodFriend)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var goalsParameter = goals != null ?
                new ObjectParameter("Goals", goals) :
                new ObjectParameter("Goals", typeof(string));
    
            var friendsNetworkParameter = friendsNetwork != null ?
                new ObjectParameter("FriendsNetwork", friendsNetwork) :
                new ObjectParameter("FriendsNetwork", typeof(string));
    
            var friendLaughParameter = friendLaugh != null ?
                new ObjectParameter("FriendLaugh", friendLaugh) :
                new ObjectParameter("FriendLaugh", typeof(string));
    
            var houseImprovementsParameter = houseImprovements != null ?
                new ObjectParameter("HouseImprovements", houseImprovements) :
                new ObjectParameter("HouseImprovements", typeof(string));
    
            var careAboutParameter = careAbout != null ?
                new ObjectParameter("CareAbout", careAbout) :
                new ObjectParameter("CareAbout", typeof(string));
    
            var organizedLifeParameter = organizedLife != null ?
                new ObjectParameter("OrganizedLife", organizedLife) :
                new ObjectParameter("OrganizedLife", typeof(string));
    
            var financesParameter = finances != null ?
                new ObjectParameter("Finances", finances) :
                new ObjectParameter("Finances", typeof(string));
    
            var homeEntertainingParameter = homeEntertaining != null ?
                new ObjectParameter("HomeEntertaining", homeEntertaining) :
                new ObjectParameter("HomeEntertaining", typeof(string));
    
            var caringforChildrenParameter = caringforChildren != null ?
                new ObjectParameter("CaringforChildren", caringforChildren) :
                new ObjectParameter("CaringforChildren", typeof(string));
    
            var romanceinRelationParameter = romanceinRelation != null ?
                new ObjectParameter("RomanceinRelation", romanceinRelation) :
                new ObjectParameter("RomanceinRelation", typeof(string));
    
            var socializingParameter = socializing != null ?
                new ObjectParameter("Socializing", socializing) :
                new ObjectParameter("Socializing", typeof(string));
    
            var homeEnvironmentParameter = homeEnvironment != null ?
                new ObjectParameter("HomeEnvironment", homeEnvironment) :
                new ObjectParameter("HomeEnvironment", typeof(string));
    
            var sharingBeliefsParameter = sharingBeliefs != null ?
                new ObjectParameter("SharingBeliefs", sharingBeliefs) :
                new ObjectParameter("SharingBeliefs", typeof(string));
    
            var physicalFitParameter = physicalFit != null ?
                new ObjectParameter("PhysicalFit", physicalFit) :
                new ObjectParameter("PhysicalFit", typeof(string));
    
            var calmDuringCrisisParameter = calmDuringCrisis != null ?
                new ObjectParameter("CalmDuringCrisis", calmDuringCrisis) :
                new ObjectParameter("CalmDuringCrisis", typeof(string));
    
            var thoughtsAndfeelingsParameter = thoughtsAndfeelings != null ?
                new ObjectParameter("ThoughtsAndfeelings", thoughtsAndfeelings) :
                new ObjectParameter("ThoughtsAndfeelings", typeof(string));
    
            var helpingFortunatesParameter = helpingFortunates != null ?
                new ObjectParameter("HelpingFortunates", helpingFortunates) :
                new ObjectParameter("HelpingFortunates", typeof(string));
    
            var resolveConflictParameter = resolveConflict != null ?
                new ObjectParameter("ResolveConflict", resolveConflict) :
                new ObjectParameter("ResolveConflict", typeof(string));
    
            var adventuresParameter = adventures != null ?
                new ObjectParameter("Adventures", adventures) :
                new ObjectParameter("Adventures", typeof(string));
    
            var knowledgeAndAwarenessParameter = knowledgeAndAwareness != null ?
                new ObjectParameter("KnowledgeAndAwareness", knowledgeAndAwareness) :
                new ObjectParameter("KnowledgeAndAwareness", typeof(string));
    
            var professionalPlanningParameter = professionalPlanning != null ?
                new ObjectParameter("ProfessionalPlanning", professionalPlanning) :
                new ObjectParameter("ProfessionalPlanning", typeof(string));
    
            var eventsUnderstandingParameter = eventsUnderstanding != null ?
                new ObjectParameter("EventsUnderstanding", eventsUnderstanding) :
                new ObjectParameter("EventsUnderstanding", typeof(string));
    
            var findingPleasureParameter = findingPleasure != null ?
                new ObjectParameter("FindingPleasure", findingPleasure) :
                new ObjectParameter("FindingPleasure", typeof(string));
    
            var cultureAndTraditionParameter = cultureAndTradition != null ?
                new ObjectParameter("CultureAndTradition", cultureAndTradition) :
                new ObjectParameter("CultureAndTradition", typeof(string));
    
            var creativeSolutionsParameter = creativeSolutions != null ?
                new ObjectParameter("CreativeSolutions", creativeSolutions) :
                new ObjectParameter("CreativeSolutions", typeof(string));
    
            var makingFriendsParameter = makingFriends != null ?
                new ObjectParameter("MakingFriends", makingFriends) :
                new ObjectParameter("MakingFriends", typeof(string));
    
            var cookingForFamilyParameter = cookingForFamily != null ?
                new ObjectParameter("CookingForFamily", cookingForFamily) :
                new ObjectParameter("CookingForFamily", typeof(string));
    
            var provideIncomeforFamilyParameter = provideIncomeforFamily != null ?
                new ObjectParameter("ProvideIncomeforFamily", provideIncomeforFamily) :
                new ObjectParameter("ProvideIncomeforFamily", typeof(string));
    
            var householdSchedulesParameter = householdSchedules != null ?
                new ObjectParameter("HouseholdSchedules", householdSchedules) :
                new ObjectParameter("HouseholdSchedules", typeof(string));
    
            var beingAgoodFriendParameter = beingAgoodFriend != null ?
                new ObjectParameter("BeingAgoodFriend", beingAgoodFriend) :
                new ObjectParameter("BeingAgoodFriend", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE_PERSONALCHOICES", profileIdParameter, goalsParameter, friendsNetworkParameter, friendLaughParameter, houseImprovementsParameter, careAboutParameter, organizedLifeParameter, financesParameter, homeEntertainingParameter, caringforChildrenParameter, romanceinRelationParameter, socializingParameter, homeEnvironmentParameter, sharingBeliefsParameter, physicalFitParameter, calmDuringCrisisParameter, thoughtsAndfeelingsParameter, helpingFortunatesParameter, resolveConflictParameter, adventuresParameter, knowledgeAndAwarenessParameter, professionalPlanningParameter, eventsUnderstandingParameter, findingPleasureParameter, cultureAndTraditionParameter, creativeSolutionsParameter, makingFriendsParameter, cookingForFamilyParameter, provideIncomeforFamilyParameter, householdSchedulesParameter, beingAgoodFriendParameter);
        }
    
        public virtual int USP_WE_INSERT_PROFILE_PERSONALDETAILS(Nullable<int> profileId, string profileName, string profileLastName, string email, string dateofBirth, string age, string mobile, string countryCode, string city, string country, string state, string zipcode, string jobCity, string jobCountry, string jobState, string jobZipcode, Nullable<bool> isSameasAbove, string fBLink, string instaLink, string twitterLink, string socialMediaLink, string introduction)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var profileNameParameter = profileName != null ?
                new ObjectParameter("ProfileName", profileName) :
                new ObjectParameter("ProfileName", typeof(string));
    
            var profileLastNameParameter = profileLastName != null ?
                new ObjectParameter("ProfileLastName", profileLastName) :
                new ObjectParameter("ProfileLastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var dateofBirthParameter = dateofBirth != null ?
                new ObjectParameter("DateofBirth", dateofBirth) :
                new ObjectParameter("DateofBirth", typeof(string));
    
            var ageParameter = age != null ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(string));
    
            var jobCityParameter = jobCity != null ?
                new ObjectParameter("JobCity", jobCity) :
                new ObjectParameter("JobCity", typeof(string));
    
            var jobCountryParameter = jobCountry != null ?
                new ObjectParameter("JobCountry", jobCountry) :
                new ObjectParameter("JobCountry", typeof(string));
    
            var jobStateParameter = jobState != null ?
                new ObjectParameter("JobState", jobState) :
                new ObjectParameter("JobState", typeof(string));
    
            var jobZipcodeParameter = jobZipcode != null ?
                new ObjectParameter("JobZipcode", jobZipcode) :
                new ObjectParameter("JobZipcode", typeof(string));
    
            var isSameasAboveParameter = isSameasAbove.HasValue ?
                new ObjectParameter("IsSameasAbove", isSameasAbove) :
                new ObjectParameter("IsSameasAbove", typeof(bool));
    
            var fBLinkParameter = fBLink != null ?
                new ObjectParameter("FBLink", fBLink) :
                new ObjectParameter("FBLink", typeof(string));
    
            var instaLinkParameter = instaLink != null ?
                new ObjectParameter("InstaLink", instaLink) :
                new ObjectParameter("InstaLink", typeof(string));
    
            var twitterLinkParameter = twitterLink != null ?
                new ObjectParameter("TwitterLink", twitterLink) :
                new ObjectParameter("TwitterLink", typeof(string));
    
            var socialMediaLinkParameter = socialMediaLink != null ?
                new ObjectParameter("SocialMediaLink", socialMediaLink) :
                new ObjectParameter("SocialMediaLink", typeof(string));
    
            var introductionParameter = introduction != null ?
                new ObjectParameter("Introduction", introduction) :
                new ObjectParameter("Introduction", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE_PERSONALDETAILS", profileIdParameter, profileNameParameter, profileLastNameParameter, emailParameter, dateofBirthParameter, ageParameter, mobileParameter, countryCodeParameter, cityParameter, countryParameter, stateParameter, zipcodeParameter, jobCityParameter, jobCountryParameter, jobStateParameter, jobZipcodeParameter, isSameasAboveParameter, fBLinkParameter, instaLinkParameter, twitterLinkParameter, socialMediaLinkParameter, introductionParameter);
        }
    
        public virtual int USP_WE_INSERT_PROFILE_PERSONALVIEWS(Nullable<int> profileId, Nullable<int> faithInGod, Nullable<int> religion, Nullable<int> caste, Nullable<int> superstitious, Nullable<int> astrology, Nullable<int> food, Nullable<int> outsideEating, Nullable<int> movies, Nullable<int> onRelaxing, Nullable<int> travel, Nullable<int> shopping, Nullable<int> spending, Nullable<int> beingSelf, Nullable<int> humor, Nullable<int> anxious, Nullable<int> tension, Nullable<int> speakingMind, Nullable<int> sadTimes, Nullable<int> angry, Nullable<int> talkative, Nullable<int> fate, Nullable<int> selfControl, Nullable<int> misUnderstood, Nullable<int> achieveGoals, Nullable<int> caring, Nullable<int> systematic, Nullable<int> creativity, Nullable<int> forgiving, Nullable<int> sensitivity, Nullable<int> admittingFaults, Nullable<int> ego, Nullable<int> friendship, Nullable<int> dailyChores, Nullable<int> tolerance, Nullable<int> techSavvy, Nullable<int> internet, Nullable<int> politics, Nullable<int> society, Nullable<int> takingInitiative, Nullable<int> familyValues)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var faithInGodParameter = faithInGod.HasValue ?
                new ObjectParameter("FaithInGod", faithInGod) :
                new ObjectParameter("FaithInGod", typeof(int));
    
            var religionParameter = religion.HasValue ?
                new ObjectParameter("Religion", religion) :
                new ObjectParameter("Religion", typeof(int));
    
            var casteParameter = caste.HasValue ?
                new ObjectParameter("Caste", caste) :
                new ObjectParameter("Caste", typeof(int));
    
            var superstitiousParameter = superstitious.HasValue ?
                new ObjectParameter("Superstitious", superstitious) :
                new ObjectParameter("Superstitious", typeof(int));
    
            var astrologyParameter = astrology.HasValue ?
                new ObjectParameter("Astrology", astrology) :
                new ObjectParameter("Astrology", typeof(int));
    
            var foodParameter = food.HasValue ?
                new ObjectParameter("Food", food) :
                new ObjectParameter("Food", typeof(int));
    
            var outsideEatingParameter = outsideEating.HasValue ?
                new ObjectParameter("OutsideEating", outsideEating) :
                new ObjectParameter("OutsideEating", typeof(int));
    
            var moviesParameter = movies.HasValue ?
                new ObjectParameter("Movies", movies) :
                new ObjectParameter("Movies", typeof(int));
    
            var onRelaxingParameter = onRelaxing.HasValue ?
                new ObjectParameter("OnRelaxing", onRelaxing) :
                new ObjectParameter("OnRelaxing", typeof(int));
    
            var travelParameter = travel.HasValue ?
                new ObjectParameter("Travel", travel) :
                new ObjectParameter("Travel", typeof(int));
    
            var shoppingParameter = shopping.HasValue ?
                new ObjectParameter("Shopping", shopping) :
                new ObjectParameter("Shopping", typeof(int));
    
            var spendingParameter = spending.HasValue ?
                new ObjectParameter("Spending", spending) :
                new ObjectParameter("Spending", typeof(int));
    
            var beingSelfParameter = beingSelf.HasValue ?
                new ObjectParameter("BeingSelf", beingSelf) :
                new ObjectParameter("BeingSelf", typeof(int));
    
            var humorParameter = humor.HasValue ?
                new ObjectParameter("Humor", humor) :
                new ObjectParameter("Humor", typeof(int));
    
            var anxiousParameter = anxious.HasValue ?
                new ObjectParameter("Anxious", anxious) :
                new ObjectParameter("Anxious", typeof(int));
    
            var tensionParameter = tension.HasValue ?
                new ObjectParameter("Tension", tension) :
                new ObjectParameter("Tension", typeof(int));
    
            var speakingMindParameter = speakingMind.HasValue ?
                new ObjectParameter("SpeakingMind", speakingMind) :
                new ObjectParameter("SpeakingMind", typeof(int));
    
            var sadTimesParameter = sadTimes.HasValue ?
                new ObjectParameter("SadTimes", sadTimes) :
                new ObjectParameter("SadTimes", typeof(int));
    
            var angryParameter = angry.HasValue ?
                new ObjectParameter("Angry", angry) :
                new ObjectParameter("Angry", typeof(int));
    
            var talkativeParameter = talkative.HasValue ?
                new ObjectParameter("Talkative", talkative) :
                new ObjectParameter("Talkative", typeof(int));
    
            var fateParameter = fate.HasValue ?
                new ObjectParameter("Fate", fate) :
                new ObjectParameter("Fate", typeof(int));
    
            var selfControlParameter = selfControl.HasValue ?
                new ObjectParameter("SelfControl", selfControl) :
                new ObjectParameter("SelfControl", typeof(int));
    
            var misUnderstoodParameter = misUnderstood.HasValue ?
                new ObjectParameter("MisUnderstood", misUnderstood) :
                new ObjectParameter("MisUnderstood", typeof(int));
    
            var achieveGoalsParameter = achieveGoals.HasValue ?
                new ObjectParameter("AchieveGoals", achieveGoals) :
                new ObjectParameter("AchieveGoals", typeof(int));
    
            var caringParameter = caring.HasValue ?
                new ObjectParameter("Caring", caring) :
                new ObjectParameter("Caring", typeof(int));
    
            var systematicParameter = systematic.HasValue ?
                new ObjectParameter("Systematic", systematic) :
                new ObjectParameter("Systematic", typeof(int));
    
            var creativityParameter = creativity.HasValue ?
                new ObjectParameter("Creativity", creativity) :
                new ObjectParameter("Creativity", typeof(int));
    
            var forgivingParameter = forgiving.HasValue ?
                new ObjectParameter("Forgiving", forgiving) :
                new ObjectParameter("Forgiving", typeof(int));
    
            var sensitivityParameter = sensitivity.HasValue ?
                new ObjectParameter("Sensitivity", sensitivity) :
                new ObjectParameter("Sensitivity", typeof(int));
    
            var admittingFaultsParameter = admittingFaults.HasValue ?
                new ObjectParameter("AdmittingFaults", admittingFaults) :
                new ObjectParameter("AdmittingFaults", typeof(int));
    
            var egoParameter = ego.HasValue ?
                new ObjectParameter("Ego", ego) :
                new ObjectParameter("Ego", typeof(int));
    
            var friendshipParameter = friendship.HasValue ?
                new ObjectParameter("Friendship", friendship) :
                new ObjectParameter("Friendship", typeof(int));
    
            var dailyChoresParameter = dailyChores.HasValue ?
                new ObjectParameter("DailyChores", dailyChores) :
                new ObjectParameter("DailyChores", typeof(int));
    
            var toleranceParameter = tolerance.HasValue ?
                new ObjectParameter("Tolerance", tolerance) :
                new ObjectParameter("Tolerance", typeof(int));
    
            var techSavvyParameter = techSavvy.HasValue ?
                new ObjectParameter("TechSavvy", techSavvy) :
                new ObjectParameter("TechSavvy", typeof(int));
    
            var internetParameter = internet.HasValue ?
                new ObjectParameter("Internet", internet) :
                new ObjectParameter("Internet", typeof(int));
    
            var politicsParameter = politics.HasValue ?
                new ObjectParameter("Politics", politics) :
                new ObjectParameter("Politics", typeof(int));
    
            var societyParameter = society.HasValue ?
                new ObjectParameter("Society", society) :
                new ObjectParameter("Society", typeof(int));
    
            var takingInitiativeParameter = takingInitiative.HasValue ?
                new ObjectParameter("TakingInitiative", takingInitiative) :
                new ObjectParameter("TakingInitiative", typeof(int));
    
            var familyValuesParameter = familyValues.HasValue ?
                new ObjectParameter("FamilyValues", familyValues) :
                new ObjectParameter("FamilyValues", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE_PERSONALVIEWS", profileIdParameter, faithInGodParameter, religionParameter, casteParameter, superstitiousParameter, astrologyParameter, foodParameter, outsideEatingParameter, moviesParameter, onRelaxingParameter, travelParameter, shoppingParameter, spendingParameter, beingSelfParameter, humorParameter, anxiousParameter, tensionParameter, speakingMindParameter, sadTimesParameter, angryParameter, talkativeParameter, fateParameter, selfControlParameter, misUnderstoodParameter, achieveGoalsParameter, caringParameter, systematicParameter, creativityParameter, forgivingParameter, sensitivityParameter, admittingFaultsParameter, egoParameter, friendshipParameter, dailyChoresParameter, toleranceParameter, techSavvyParameter, internetParameter, politicsParameter, societyParameter, takingInitiativeParameter, familyValuesParameter);
        }
    
        public virtual ObjectResult<string> usp_WE_Insert_Profile_Photo(Nullable<int> profileId, string photoNameExt, ObjectParameter optimizedphotourl)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var photoNameExtParameter = photoNameExt != null ?
                new ObjectParameter("PhotoNameExt", photoNameExt) :
                new ObjectParameter("PhotoNameExt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_WE_Insert_Profile_Photo", profileIdParameter, photoNameExtParameter, optimizedphotourl);
        }
    
        public virtual ObjectResult<string> USP_WE_INSERT_PROFILE_PIC(Nullable<int> profileId, string photoNameExt, ObjectParameter optimizedphotourl)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var photoNameExtParameter = photoNameExt != null ?
                new ObjectParameter("PhotoNameExt", photoNameExt) :
                new ObjectParameter("PhotoNameExt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_WE_INSERT_PROFILE_PIC", profileIdParameter, photoNameExtParameter, optimizedphotourl);
        }
    
        public virtual int USP_WE_INSERT_PROFILE_SELFDESCRIPTION(Nullable<int> profileId, string peopleNoticeFirstThing, string mostThankful, string mostInfluentPerson, string cannotLiveWithout, string spendLeisureTime, string mostProudOf, string lovablePerson, string importantQualityofaPerson, string additionalInfo)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var peopleNoticeFirstThingParameter = peopleNoticeFirstThing != null ?
                new ObjectParameter("PeopleNoticeFirstThing", peopleNoticeFirstThing) :
                new ObjectParameter("PeopleNoticeFirstThing", typeof(string));
    
            var mostThankfulParameter = mostThankful != null ?
                new ObjectParameter("MostThankful", mostThankful) :
                new ObjectParameter("MostThankful", typeof(string));
    
            var mostInfluentPersonParameter = mostInfluentPerson != null ?
                new ObjectParameter("MostInfluentPerson", mostInfluentPerson) :
                new ObjectParameter("MostInfluentPerson", typeof(string));
    
            var cannotLiveWithoutParameter = cannotLiveWithout != null ?
                new ObjectParameter("CannotLiveWithout", cannotLiveWithout) :
                new ObjectParameter("CannotLiveWithout", typeof(string));
    
            var spendLeisureTimeParameter = spendLeisureTime != null ?
                new ObjectParameter("SpendLeisureTime", spendLeisureTime) :
                new ObjectParameter("SpendLeisureTime", typeof(string));
    
            var mostProudOfParameter = mostProudOf != null ?
                new ObjectParameter("MostProudOf", mostProudOf) :
                new ObjectParameter("MostProudOf", typeof(string));
    
            var lovablePersonParameter = lovablePerson != null ?
                new ObjectParameter("LovablePerson", lovablePerson) :
                new ObjectParameter("LovablePerson", typeof(string));
    
            var importantQualityofaPersonParameter = importantQualityofaPerson != null ?
                new ObjectParameter("ImportantQualityofaPerson", importantQualityofaPerson) :
                new ObjectParameter("ImportantQualityofaPerson", typeof(string));
    
            var additionalInfoParameter = additionalInfo != null ?
                new ObjectParameter("AdditionalInfo", additionalInfo) :
                new ObjectParameter("AdditionalInfo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE_SELFDESCRIPTION", profileIdParameter, peopleNoticeFirstThingParameter, mostThankfulParameter, mostInfluentPersonParameter, cannotLiveWithoutParameter, spendLeisureTimeParameter, mostProudOfParameter, lovablePersonParameter, importantQualityofaPersonParameter, additionalInfoParameter);
        }
    
        public virtual int USP_WE_INSERT_PROFILE_WHOAMI(Nullable<int> profileId, string thankfulFor, string lifeSkills, string thingsCantLiveWithout, string friendsDescribedAs)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var thankfulForParameter = thankfulFor != null ?
                new ObjectParameter("ThankfulFor", thankfulFor) :
                new ObjectParameter("ThankfulFor", typeof(string));
    
            var lifeSkillsParameter = lifeSkills != null ?
                new ObjectParameter("LifeSkills", lifeSkills) :
                new ObjectParameter("LifeSkills", typeof(string));
    
            var thingsCantLiveWithoutParameter = thingsCantLiveWithout != null ?
                new ObjectParameter("ThingsCantLiveWithout", thingsCantLiveWithout) :
                new ObjectParameter("ThingsCantLiveWithout", typeof(string));
    
            var friendsDescribedAsParameter = friendsDescribedAs != null ?
                new ObjectParameter("FriendsDescribedAs", friendsDescribedAs) :
                new ObjectParameter("FriendsDescribedAs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_PROFILE_WHOAMI", profileIdParameter, thankfulForParameter, lifeSkillsParameter, thingsCantLiveWithoutParameter, friendsDescribedAsParameter);
        }
    
        public virtual int USP_WE_INSERT_USER_ACTIVATION_CODE(Nullable<int> profileID, string activationCode)
        {
            var profileIDParameter = profileID.HasValue ?
                new ObjectParameter("ProfileID", profileID) :
                new ObjectParameter("ProfileID", typeof(int));
    
            var activationCodeParameter = activationCode != null ?
                new ObjectParameter("ActivationCode", activationCode) :
                new ObjectParameter("ActivationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_USER_ACTIVATION_CODE", profileIDParameter, activationCodeParameter);
        }
    
        public virtual ObjectResult<string> USP_WE_INSERT_USER_PACKAGE(Nullable<int> profileId, Nullable<int> packageId, string transaction_Id, string payment_From)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var packageIdParameter = packageId.HasValue ?
                new ObjectParameter("PackageId", packageId) :
                new ObjectParameter("PackageId", typeof(int));
    
            var transaction_IdParameter = transaction_Id != null ?
                new ObjectParameter("Transaction_Id", transaction_Id) :
                new ObjectParameter("Transaction_Id", typeof(string));
    
            var payment_FromParameter = payment_From != null ?
                new ObjectParameter("Payment_From", payment_From) :
                new ObjectParameter("Payment_From", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_WE_INSERT_USER_PACKAGE", profileIdParameter, packageIdParameter, transaction_IdParameter, payment_FromParameter);
        }
    
        public virtual int USP_WE_INSERT_WHO_VIEWED_MY_PROFILE(Nullable<int> profileId, Nullable<int> viewedProfileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var viewedProfileIdParameter = viewedProfileId.HasValue ?
                new ObjectParameter("ViewedProfileId", viewedProfileId) :
                new ObjectParameter("ViewedProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_INSERT_WHO_VIEWED_MY_PROFILE", profileIdParameter, viewedProfileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_RELIGION_CASTE_SUBCASTE_Result> USP_WE_RELIGION_CASTE_SUBCASTE(Nullable<int> rELIGION_ID, Nullable<int> cASTE_ID, Nullable<int> fLAG)
        {
            var rELIGION_IDParameter = rELIGION_ID.HasValue ?
                new ObjectParameter("RELIGION_ID", rELIGION_ID) :
                new ObjectParameter("RELIGION_ID", typeof(int));
    
            var cASTE_IDParameter = cASTE_ID.HasValue ?
                new ObjectParameter("CASTE_ID", cASTE_ID) :
                new ObjectParameter("CASTE_ID", typeof(int));
    
            var fLAGParameter = fLAG.HasValue ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_RELIGION_CASTE_SUBCASTE_Result>("USP_WE_RELIGION_CASTE_SUBCASTE", rELIGION_IDParameter, cASTE_IDParameter, fLAGParameter);
        }
    
        public virtual int USP_WE_REM_USER_FAVOURITES(Nullable<int> profileId, Nullable<int> favouriteProfileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var favouriteProfileIdParameter = favouriteProfileId.HasValue ?
                new ObjectParameter("FavouriteProfileId", favouriteProfileId) :
                new ObjectParameter("FavouriteProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_REM_USER_FAVOURITES", profileIdParameter, favouriteProfileIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_WE_SET_USER_DEFAULT_PHOTO(Nullable<int> profileId, Nullable<int> photoId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var photoIdParameter = photoId.HasValue ?
                new ObjectParameter("PhotoId", photoId) :
                new ObjectParameter("PhotoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_WE_SET_USER_DEFAULT_PHOTO", profileIdParameter, photoIdParameter);
        }
    
        public virtual int USP_WE_SET_USER_FAVOURITES(Nullable<int> profileId, Nullable<int> favouriteProfileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var favouriteProfileIdParameter = favouriteProfileId.HasValue ?
                new ObjectParameter("FavouriteProfileId", favouriteProfileId) :
                new ObjectParameter("FavouriteProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_SET_USER_FAVOURITES", profileIdParameter, favouriteProfileIdParameter);
        }
    
        public virtual int USP_WE_USER_ACTIVATION(ObjectParameter sResult, Nullable<System.Guid> activationCode)
        {
            var activationCodeParameter = activationCode.HasValue ?
                new ObjectParameter("ActivationCode", activationCode) :
                new ObjectParameter("ActivationCode", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WE_USER_ACTIVATION", sResult, activationCodeParameter);
        }
    
        public virtual ObjectResult<string> USP_WEVAHA_ISUER_PACKAGE_ACTIVE(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_WEVAHA_ISUER_PACKAGE_ACTIVE", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WE_VALIDATE_USER(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WE_VALIDATE_USER", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WEvaha_Get_ProfileId(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WEvaha_Get_ProfileId", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WEvaha_Get_User_By_ResetPasswordCode(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WEvaha_Get_User_By_ResetPasswordCode", idParameter);
        }
    
        public virtual int WEvaha_Get_UserActivationCode(ObjectParameter sResult, Nullable<System.Guid> activationCode)
        {
            var activationCodeParameter = activationCode.HasValue ?
                new ObjectParameter("ActivationCode", activationCode) :
                new ObjectParameter("ActivationCode", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEvaha_Get_UserActivationCode", sResult, activationCodeParameter);
        }
    
        public virtual ObjectResult<string> WEvaha_Get_UserEmailId(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WEvaha_Get_UserEmailId", profileIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WEvaha_Get_UserId(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WEvaha_Get_UserId", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> WEvaha_Get_UserName(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WEvaha_Get_UserName", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WEvaha_Get_UserStatus(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WEvaha_Get_UserStatus", usernameParameter);
        }
    
        public virtual int WEvaha_Insert_ResetPasswordCode(string username, string passwordResetCode)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordResetCodeParameter = passwordResetCode != null ?
                new ObjectParameter("PasswordResetCode", passwordResetCode) :
                new ObjectParameter("PasswordResetCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEvaha_Insert_ResetPasswordCode", usernameParameter, passwordResetCodeParameter);
        }
    
        public virtual int WEvaha_Insert_User_Registration(ObjectParameter profileId, string profileName, string email, string gender, string seekingGender, string password, string activationCode, string geolocation)
        {
            var profileNameParameter = profileName != null ?
                new ObjectParameter("ProfileName", profileName) :
                new ObjectParameter("ProfileName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var seekingGenderParameter = seekingGender != null ?
                new ObjectParameter("SeekingGender", seekingGender) :
                new ObjectParameter("SeekingGender", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var activationCodeParameter = activationCode != null ?
                new ObjectParameter("ActivationCode", activationCode) :
                new ObjectParameter("ActivationCode", typeof(string));
    
            var geolocationParameter = geolocation != null ?
                new ObjectParameter("Geolocation", geolocation) :
                new ObjectParameter("Geolocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEvaha_Insert_User_Registration", profileId, profileNameParameter, emailParameter, genderParameter, seekingGenderParameter, passwordParameter, activationCodeParameter, geolocationParameter);
        }
    
        public virtual int WEvaha_Update_NewPassword(ObjectParameter result, Nullable<int> userId, string password)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEvaha_Update_NewPassword", result, userIdParameter, passwordParameter);
        }
    
        public virtual int WEvaha_User_FullName(ObjectParameter result, string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEvaha_User_FullName", result, usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WEvaha_Validate_User(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WEvaha_Validate_User", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_PROFILE_ABOUTMYSELF_BY_ID_Result> USP_WE_GET_PROFILE_ABOUTMYSELF_BY_ID(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_PROFILE_ABOUTMYSELF_BY_ID_Result>("USP_WE_GET_PROFILE_ABOUTMYSELF_BY_ID", profileIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WE_ISFULLYREGISTERED(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WE_ISFULLYREGISTERED", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_COMPATIBLE_MATCHES_Result> USP_WE_GET_COMPATIBLE_MATCHES(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_COMPATIBLE_MATCHES_Result>("USP_WE_GET_COMPATIBLE_MATCHES", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_USER_COMPATABLE_MATCHES_Result> USP_WE_GET_USER_COMPATABLE_MATCHES(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_USER_COMPATABLE_MATCHES_Result>("USP_WE_GET_USER_COMPATABLE_MATCHES", profileIdParameter);
        }
    
        public virtual ObjectResult<USP_WE_GET_TOTAL__RECENT_VISITORS_Result> USP_WE_GET_TOTAL__RECENT_VISITORS(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_WE_GET_TOTAL__RECENT_VISITORS_Result>("USP_WE_GET_TOTAL__RECENT_VISITORS", profileIdParameter);
        }
    }
}
