using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WE.BusinessEntities
{
    public class Profile_PersonalViews
    {
        public int FaithInGod { get; set; }
        public List<SelectListItem> FaithInGodOpti { get; set; }
        public int Religion { get; set; }
        public List<SelectListItem> ReligionOpti { get; set; }
        public int Caste { get; set; }
        public List<SelectListItem> CasteOpti { get; set; }
        public int Superstitious { get; set; }
        public List<SelectListItem> SuperstitiousOpti { get; set; }
        public int Astrology { get; set; }
        public List<SelectListItem> AstrologyOpti { get; set; }
        public int Food { get; set; }
        public List<SelectListItem> FoodOpti { get; set; }
        public int OutsideEating { get; set; }
        public List<SelectListItem> OutsideEatingOpti { get; set; }
        public int Movies { get; set; }
        public List<SelectListItem> MoviesOpti { get; set; }
        public int OnRelaxing { get; set; }
        public List<SelectListItem> OnRelaxingOpti { get; set; }
        public int Travel { get; set; }
        public List<SelectListItem> TravelOpti { get; set; }
        public int Shopping { get; set; }
        public List<SelectListItem> ShoppingOpti { get; set; }
        public int Spending { get; set; }
        public List<SelectListItem> SpendingOpti { get; set; }
        public int BeingSelf { get; set; }
        public List<SelectListItem> BeingSelfOpti { get; set; }
        public int Humor { get; set; }
        public List<SelectListItem> HumorOpti { get; set; }
        public int Anxious { get; set; }
        public List<SelectListItem> AnxiousOpti { get; set; }
        public int Tension { get; set; }
        public List<SelectListItem> TensionOpti { get; set; }
        public int SpeakingMind { get; set; }
        public List<SelectListItem> SpeakingMindOpti { get; set; }
        public int SadTimes { get; set; }
        public List<SelectListItem> SadTimesOpti { get; set; }
        public int Angry { get; set; }
        public List<SelectListItem> AngryOpti { get; set; }
        public int Talkative { get; set; }
        public List<SelectListItem> TalkativeOpti { get; set; }
        public int Fate { get; set; }
        public List<SelectListItem> FateOpti { get; set; }
        public int SelfControl { get; set; }
        public List<SelectListItem> SelfControlOpti { get; set; }
        public int MisUnderstood { get; set; }
        public List<SelectListItem> MisUnderstoodOpti { get; set; }
        public int AchieveGoals { get; set; }
        public List<SelectListItem> AchieveGoalsOpti { get; set; }
        public int Caring { get; set; }
        public List<SelectListItem> CaringOpti { get; set; }
        public int Systematic { get; set; }
        public List<SelectListItem> SystematicOpti { get; set; }
        public int Creativity { get; set; }
        public List<SelectListItem> CreativityOpti { get; set; }
        public int Forgiving { get; set; }
        public List<SelectListItem> ForgivingOpti { get; set; }
        public int Sensitivity { get; set; }
        public List<SelectListItem> SensitivityOpti { get; set; }
        public int AdmittingFaults { get; set; }
        public List<SelectListItem> AdmittingFaultsOpti { get; set; }
        public int Ego { get; set; }
        public List<SelectListItem> EgoOpti { get; set; }
        public int Friendship { get; set; }
        public List<SelectListItem> FriendshipOpti { get; set; }
        public int DailyChores { get; set; }
        public List<SelectListItem> DailyChoresOpti { get; set; }
        public int Tolerance { get; set; }
        public List<SelectListItem> ToleranceOpti { get; set; }
        public int TechSavvy { get; set; }
        public List<SelectListItem> TechSavvyOpti { get; set; }
        public int Internet { get; set; }
        public List<SelectListItem> InternetOpti { get; set; }
        public int Politics { get; set; }
        public List<SelectListItem> PoliticsOpti { get; set; }
        public int Society { get; set; }
        public List<SelectListItem> SocietyOpti { get; set; }
        public int TakingInitiative { get; set; }
        public List<SelectListItem> TakingInitiativeOpti { get; set; }
        public int FamilyValues { get; set; }
        public List<SelectListItem> FamilyValuesOpti { get; set; }
        //public string FaithInGod { get; set; }
        //public string Religion { get; set; }
        //public string Caste { get; set; }
        //public string Superstitious { get; set; }
        //public string Astrology { get; set; }
        //public string Food { get; set; }
        //public string OutsideEating { get; set; }
        //public string Movies { get; set; }
        //public string OnRelaxing { get; set; }
        //public string Travel { get; set; }
        //public string Shopping { get; set; }
        //public string Spending { get; set; }
        //public string BeingSelf { get; set; }
        //public string Humor { get; set; }
        //public string Anxious { get; set; }
        //public string Tension { get; set; }
        //public string SpeakingMind { get; set; }
        //public string SadTimes { get; set; }
        //public string Angry { get; set; }
        //public string Talkative { get; set; }
        //public string Fate { get; set; }
        //public string SelfControl { get; set; }
        //public string MisUnderstood { get; set; }
        //public string AchieveGoals { get; set; }
        //public string Caring { get; set; }
        //public string Systematic { get; set; }
        //public string Creativity { get; set; }
        //public string Forgiving { get; set; }
        //public string Sensitivity { get; set; }
        //public string AdmittingFaults { get; set; }
        //public string Ego { get; set; }
        //public string Friendship { get; set; }
        //public string DailyChores { get; set; }
        //public string Tolerance { get; set; }
        //public string TechSavvy { get; set; }
        //public string Internet { get; set; }
        //public string Politics { get; set; }
        //public string Society { get; set; }
        //public string TakingInitiative { get; set; }
        //public string FamilyValues { get; set; }
    }
}